//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Source/Camera/CameraMovementActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraMovementActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraMovementActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraMovementActions"",
    ""maps"": [
        {
            ""name"": ""ClickAndDrag"",
            ""id"": ""af41bf43-4588-4148-ab83-c5b63f8b1de9"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""647b0c9b-597b-425a-b09d-0954d1cd9d35"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""3d43b5a7-dde8-4fd7-8902-388a6a400e8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8034eeac-a27f-4aa8-86b8-f4e2982bd839"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67707cb5-5b51-4197-b4d2-6ad8abd8bfd8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse"",
            ""bindingGroup"": ""Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // ClickAndDrag
        m_ClickAndDrag = asset.FindActionMap("ClickAndDrag", throwIfNotFound: true);
        m_ClickAndDrag_Position = m_ClickAndDrag.FindAction("Position", throwIfNotFound: true);
        m_ClickAndDrag_Click = m_ClickAndDrag.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ClickAndDrag
    private readonly InputActionMap m_ClickAndDrag;
    private IClickAndDragActions m_ClickAndDragActionsCallbackInterface;
    private readonly InputAction m_ClickAndDrag_Position;
    private readonly InputAction m_ClickAndDrag_Click;
    public struct ClickAndDragActions
    {
        private @CameraMovementActions m_Wrapper;
        public ClickAndDragActions(@CameraMovementActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_ClickAndDrag_Position;
        public InputAction @Click => m_Wrapper.m_ClickAndDrag_Click;
        public InputActionMap Get() { return m_Wrapper.m_ClickAndDrag; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClickAndDragActions set) { return set.Get(); }
        public void SetCallbacks(IClickAndDragActions instance)
        {
            if (m_Wrapper.m_ClickAndDragActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnPosition;
                @Click.started -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_ClickAndDragActionsCallbackInterface.OnClick;
            }
            m_Wrapper.m_ClickAndDragActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }
        }
    }
    public ClickAndDragActions @ClickAndDrag => new ClickAndDragActions(this);
    private int m_MouseSchemeIndex = -1;
    public InputControlScheme MouseScheme
    {
        get
        {
            if (m_MouseSchemeIndex == -1) m_MouseSchemeIndex = asset.FindControlSchemeIndex("Mouse");
            return asset.controlSchemes[m_MouseSchemeIndex];
        }
    }
    public interface IClickAndDragActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
    }
}
